apiVersion: v1
kind: Service
metadata:
  name: kubernetes-service
spec:
  selector:
    app: kubernetes-app
  ports:
    - protocol: TCP
      port: 8000       
      targetPort: 3031 
  type: ClusterIP
